// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Album string `path:"album,optional"`
}

type Response struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Artist string  `json:"artist"`
	Price  float64 `json:"price"`
}
